durid:
 cfg:
  schema: sql/cfg.sql
  
spring:
 application:
  name: share
 security:
  user:
   name: test
   password: test123
feign:
 client:
  config:
   default: 
    connectTimeout: 5000
    readTimeout: 5000
 compression:
  request: 
   enable: true
   mime-types: text/xml,application/xml,application/json
   min-request-size: 2048
  response:
   enable: true
 hystrix:
  enable: true
hystrix:
 shareSecurityContext: true
 command:
  default:
   execution:
    ioslation: 
     thread: 
      timeoutInMillisecond: 2000
   circuitBreaker:
    sleepWindowInMilliseconds: 5000
    forceClosed: false